name: Run tests shell script

on:
  push:
    branches:
      - "main"

jobs:
  run-tests-shell-script:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/tests.sh
