name: Run unit tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  run-unit-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          xcodebuild clean test \
          -project ./GithubActions.xcodeproj \
          -scheme GithubActions \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
